name: Create Asana Task on New GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-asana-task:
    runs-on: ubuntu-latest

    steps:
    - name: Create Asana Task
      env:
        ASANA_API_KEY: ${{ secrets.ASANA_API_KEY }}
        ASANA_PROJECT_ID: 1208169954646752
      run: |
        response=$(curl -s -X POST https://app.asana.com/api/1.0/tasks \
        -H "Authorization: Bearer $ASANA_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{
              "data": {
                "workspace": "1208169957145532",
                "name": "test task",
                "assignee": "Safal Jaiswal",
                "assignee_section": "To do",
                "projects": [
                  "1208169954646752"
                ]
            }')
        
        echo "Response from Asana: $response"
