name: Create Asana Task on New GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-asana-task:
    runs-on: ubuntu-latest

    steps:
    - name: Create Asana Task
      run: |
        curl -s -X POST https://app.asana.com/api/1.0/tasks \
        -H "Authorization: Bearer ${{ secrets.ASANA_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{
              "projects": ["1208169954646752"],  # Replace with your actual project ID
              "name": "${{ github.event.issue.title }}",
              "notes": "${{ github.event.issue.body }}",
              "assignee": "me",
              "workspace": "My workspace"  # Replace with your actual workspace ID
            }'
