name: Create Asana Task on New GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-asana-task:
    runs-on: ubuntu-latest

    steps:
    - name: Command to check workspace IDs
      run: |
        curl -H "Authorization: Bearer ${{ secrets.ASANA_API_KEY }}" https://app.asana.com/api/1.0/workspaces
    - name: Log JSON Payload
      run: |
        echo "{\"projects\": \"1208180556617367\", \"workspace\": \"1208169944374521\", \"name\": \"${{ github.event.issue.title }}\", \"notes\": \"${{ github.event.issue.body }}\", \"assignee\": \"me\"}"
    - name: Create Asana Task
      run: |
        curl --request POST \
          --url https://app.asana.com/api/1.0/tasks \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --header "Authorization: Bearer ${{ secrets.ASANA_API_KEY }}" \
          --data "{\"projects\": \"1208180556617367\", \"workspace\": \"1208169944374521\", \"name\": \"${{ github.event.issue.title }}\", \"notes\": \"${{ github.event.issue.body }}\", \"assignee\": \"me\"}"
